export default {
  TOKEN: 'token',
  FAVORITES: 'favoriteSymbols',
  LCH: 'layoutContentHeight',
  LANGUAGE: 'language',
  emailCheckRegex: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
  passCheckRegex: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{9,}$/, //大小写数字且不少于9位
  accountType: 'accountType',
  phoneAreaCode: [
    { code: '86', label: '中国' },
    { code: '1', label: '美国' },
    { code: '44', label: '英国' },
    { code: '81', label: '日本' },
    { code: '49', label: '德国' },
    { code: '33', label: '法国' },
    // { code: '1', label: '加拿大' },
    { code: '61', label: '澳大利亚' },
    { code: '91', label: '印度' },
    { code: '55', label: '巴西' },
    { code: '7', label: '俄罗斯' },
    { code: '82', label: '韩国' },
    { code: '52', label: '墨西哥' },
    { code: '34', label: '西班牙' },
    { code: '39', label: '意大利' },
    { code: '31', label: '荷兰' },
    { code: '41', label: '瑞士' },
    { code: '65', label: '新加坡' },
    { code: '971', label: '阿联酋' },
    { code: '27', label: '南非' },
  ],
};
